### PR TITLE
make block value public

### PR DESCRIPTION
**Pull request by Covertness**
I supported block wise on the client side of [the repository](https://github.com/Covertness/coap-rs/tree/block-wise). I hope it can reuse some codes in the repository.

### CODE REVIEW

**Comment by martindisch** [comment]
Is making the types from the `block_handler` module public as you propose enough or do you need to access the fields too? Because right now they're private.

**Comment by Covertness** [comment]
Yeah. I want them in my repo.

**Comment by martindisch** [comment]
Alright, published as 0.9.1.

**Comment by Covertness** [comment]
Thanks

**Pull request merged**
